'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class OOSPay

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''secure3dsecuritylevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secure3dsecuritylevel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''apiversion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apiversion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''terminalprovuserid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents terminalprovuserid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''terminaluserid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents terminaluserid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''terminalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents terminalid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''terminalmerchantid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents terminalmerchantid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''orderid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orderid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''customeremailaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customeremailaddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''customeripaddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customeripaddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txntype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txntype As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txnamount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txnamount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txncurrencycode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txncurrencycode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''companyname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents companyname As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txninstallmentcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txninstallmentcount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''successurl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents successurl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''errorurl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorurl As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''secure3dhash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secure3dhash As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lang As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txntimestamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txntimestamp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''refreshtime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents refreshtime As Global.System.Web.UI.WebControls.HiddenField
End Class
